
export const SIGNIN_USER_REQUEST = "SIGNIN_USER_REQUEST"
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS"
export const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR"

export const GET_SIGNIN_USER_REQUEST = "GET_SIGNIN_USER_REQUEST"
export const GET_SIGNIN_USER_SUCCESS = "GET_SIGNIN_USER_SUCCESS"
export const GET_SIGNIN_USER_ERROR = "GET_SIGNIN_USER_ERROR"

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR"

export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST"
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS"
export const CREATE_PROFILE_ERROR = "CREATE_PROFILE_ERROR"

export const CREATE_ADDRESS_REQUEST = "CREATE_ADDRESS_REQUEST"
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS"
export const CREATE_ADDRESS_ERROR = "CREATE_ADDRESS_ERROR"

export const SIGN_OUT_USER_REQUEST = "SIGN_OUT_USER_REQUEST"
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS"
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR"